// Export all homepage components
export { default as HeroSection } from './HeroSection'
export { default as MarqueeBanner } from './MarqueeBanner'
export { default as CategoryShowcase } from './CategoryShowcase'
export { default as FeaturedProducts } from './FeaturedProducts'
export { default as WhyGibbon } from './WhyGibbon'
export { default as VideoReels } from './VideoReels'
export { default as Testimonials } from './Testimonials'
export { default as Newsletter } from './Newsletter'
export { default as FAQ } from './FAQ'
export { default as PromoBanners } from './PromoBanners'
export { default as InstagramFeed } from './InstagramFeed'
export { default as BestSellers } from './BestSellers'
export { default as NewArrivals } from './NewArrivals'
export { default as FlashDeals } from './FlashDeals'
export { default as TrendingProducts } from './TrendingProducts'
export { default as BrandPromise } from './BrandPromise'
