import mongoose, { Document, Schema } from 'mongoose'

export interface IProductRecommendation extends Document {
  // Source product
  productId: mongoose.Types.ObjectId
  productHandle: string
  productTitle: string
  
  // Recommendation type
  type: 'you_may_also_like' | 'bought_together'
  
  // Recommended products
  recommendations: {
    productId: mongoose.Types.ObjectId
    productHandle: string
    productTitle: string
    productImage: string
    productPrice: number
    position: number
  }[]
  
  // Settings
  isActive: boolean
  displayLimit: number
  
  // Auto-generation settings (for future AI/analytics integration)
  isAutoGenerated: boolean
  lastAutoUpdate?: Date
  
  // Timestamps
  createdAt: Date
  updatedAt: Date
}

const ProductRecommendationSchema = new Schema<IProductRecommendation>(
  {
    productId: { type: Schema.Types.ObjectId, ref: 'Product', required: true },
    productHandle: { type: String, required: true, index: true },
    productTitle: { type: String, required: true },
    
    type: {
      type: String,
      enum: ['you_may_also_like', 'bought_together'],
      required: true
    },
    
    recommendations: [{
      productId: { type: Schema.Types.ObjectId, ref: 'Product', required: true },
      productHandle: { type: String, required: true },
      productTitle: { type: String, required: true },
      productImage: { type: String, default: '' },
      productPrice: { type: Number, default: 0 },
      position: { type: Number, default: 0 }
    }],
    
    isActive: { type: Boolean, default: true },
    displayLimit: { type: Number, default: 4 },
    
    isAutoGenerated: { type: Boolean, default: false },
    lastAutoUpdate: { type: Date }
  },
  { timestamps: true }
)

// Compound index for efficient queries
ProductRecommendationSchema.index({ productHandle: 1, type: 1 }, { unique: true })
ProductRecommendationSchema.index({ type: 1, isActive: 1 })

export default mongoose.models.ProductRecommendation || mongoose.model<IProductRecommendation>('ProductRecommendation', ProductRecommendationSchema)
